server {
    listen 8080;
    listen [::]:8080;

    server_name azureuser;

    root <WEB_ROOT>;
    index <INDEX_FILE>;

    access_log /var/log/nginx/azureuser-access.log;
    error_log /var/log/nginx/azureuser-error.log;

    location / {
        <ALLOW_DIRECTIVE>
        try_files $uri $uri/ =404;
    }
}
